datasource:
  url: jdbc:postgresql://postgres:5432/library_db
  username: postgres
  password: postgres

spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
