datasource:
  url: jdbc:h2:mem:test
  username: sa
  password: password

spring:
  application:
    name: library-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
